# Site settings
blogtitle: "Sketching ideas"
blogsubtitle: "Blogging taking notes"
author:
  name: "Gianluca Ciocci"
  email: "me@gianlucaciocci.com"
  github: "gianlucaciocci"  
  twitter: "gianlucaciocci"  
  pinterest: ""  
  linkedin: "gianlucaciocci"  
  rss: "atom.xml"
  resume: ""  
  bio: "Computers perform repetitive tasks, people solve problems!"#"Sketching notes. Just take it as it is" "DevOps playground. Just take it as it is"  
  email_md5: "md5ofemail"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gianlucaciocci.com" # the base hostname & protocol for your site
google_analytics: "gianlucaciocci"
disquis: "gianlucaciocci"


# Build settings
markdown: kramdown
highlighter: rouge

#defaults configuration
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "gianlucaciocci.com - Gianluca Ciocci personal blog"
      description: > #default website description
        Write an awesome description for your new site here. You can edit this
         line in _config.yml. It will appear in your document head meta (for
        Google search results) and in your feed.xml site description.
      comments: true


paginate: 5
paginate_path: "/blog/page:num/#five"
gems:
  - jekyll-paginate

