permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: gianlucaciocci.com
google_analytics: UA-52446115-1

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Gianluca Ciocci
title: Gianluca Ciocci
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
meta_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
meta_keywords: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
url: http://gianlucaciocci.com
production_url: http://gianlucaciocci.com
repo: https://github.com/nandomoreirame/nandomoreira-jekyll-theme
disqus_shortname: "gianlucaciocci"
rss_path: source/
author:
  name      : Gianluca Ciocci
  image     : /assets/images/author.jpg
  email     : me@gianlucaciocci.com
  url       : http://gianlucaciocci.com
  facebook  : http://facebook.com/gianlucaciocci.dev
  twitter   : http://twitter.com/gianlucaciocci
  instagram : http://instagram.com/gianlucaciocci.me
  github    : http://github.com/gianlucaciocci
  linkedin  : https://uk.linkedin.com/in/gianlucaciocci
  bio       : "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
