# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "{REMARKED}"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Blogging taking notes"

# Tagline near the site title
tagline: "Thoughts, notes and ideas"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

sass:
  sass_dir: _sass

plugins: 
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-redirect-from
 - jemoji
 - jekyll-mentions

assets:
 - favicon: "/assets/favicon"
 - favicon-dark: "/assets/favicondark"

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://gianlucaciocci.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/
- text: Cheatsheets
  url: /cheatsheets/
# - text: Enterprise DevOps Community
#   url: /entdevops/

# The shortname for your Disqus site to enable comments.
# disqus:

# Author information - author info at the bottom of the post
author_name: "Gianluca Ciocci"
author_bio: "Gianluca is a DevOps consultant spending most of his time on “getting things done” with automation - he believes that computers perform repetitive tasks and people solve problems."
author_url:  "http://gianlucaciocci.com"
author_location: "London, UK"
author_image: /images/authorimage.jpg

# Sidebar Add banner
banner_url: #"http://meetup.com/entdevops"
banner_image: #images/banner.jpeg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: #"//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
endevops_enroll_url:
# Social links in the site footer
twitter_username: "gianlucaciocci"
facebook_username:
googleplus_username:
github_username: "gianlucaciocci"
codepen_username:
dribbble_uername:
medium_username:
instagram_username:
pinterest_username:
linkedin_username: "gianlucaciocci"
email_username: "me@gianlucaciocci.com"
disqus: "gianlucaciocci"
google_analytics: "gianlucaciocci"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'


permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: false
